<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>arrow_TemplateFieldPopups_DefaultType</name>
   <tag></tag>
   <elementGuidId>70daaee6-e6c7-4596-906e-6ddd1efdd894</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-label='编辑TemplateField']//form//label[@for='Sequence']/following-sibling::div//i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-label='编辑TemplateField']//form//label[@for='Sequence']/following-sibling::div//i</value>
   </webElementProperties>
</WebElementEntity>
