<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HintTableConditionPopups_conditionFieldName</name>
   <tag></tag>
   <elementGuidId>610ed896-c22b-4464-86b4-f251d777e1de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-label='新增TemplateField']//label[@for='ConditionBeFieldId']/following-sibling::div//i[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-label='新增TemplateField']//label[@for='ConditionBeFieldId']/following-sibling::div//i[@type='text']</value>
   </webElementProperties>
</WebElementEntity>
