<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_TemplateFieldPopups_CheckRepeatY</name>
   <tag></tag>
   <elementGuidId>0c28804f-a4e0-4daa-9d82-9768e81ac0ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-label='编辑TemplateField']//form//label[@for='CheckRepeat']/following-sibling::div//label[@tabindex='-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-label='编辑TemplateField']//form//label[@for='CheckRepeat']/following-sibling::div//label[@tabindex='-1']</value>
   </webElementProperties>
</WebElementEntity>
