<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_TemplateFieldPopups_IfRequiredY</name>
   <tag></tag>
   <elementGuidId>37965abc-27f9-4fb4-97d1-ae967168c35b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-label='编辑TemplateField']//form//label[@for='Required']/following-sibling::div//label[@tabindex='0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-label='编辑TemplateField']//form//label[@for='Required']/following-sibling::div//label[@tabindex='0']</value>
   </webElementProperties>
</WebElementEntity>
