<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TemplateFieldPopups_Format_hintTable</name>
   <tag></tag>
   <elementGuidId>95d4ff02-8b97-43b6-960f-0fbbbf8cbee8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-label='编辑TemplateField']//form//label[@for='CheckRepeat']/following-sibling::div//label[@tabindex='0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-label='编辑TemplateField']//form//label[@for='CheckRepeat']/following-sibling::div//label[@tabindex='0']</value>
   </webElementProperties>
</WebElementEntity>
